// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-concepts/HeartEntry.tsx": () => import("../components/mockups/home-concepts/HeartEntry.tsx"),
  "./components/mockups/home-concepts/TheWhisper.tsx": () => import("../components/mockups/home-concepts/TheWhisper.tsx"),
  "./components/mockups/home-concepts/YourLetter.tsx": () => import("../components/mockups/home-concepts/YourLetter.tsx"),
  "./components/mockups/explore/CurrentGrid.tsx": () => import("../components/mockups/explore/CurrentGrid.tsx"),
  "./components/mockups/explore/GroupedGrid.tsx": () => import("../components/mockups/explore/GroupedGrid.tsx")
};
