/**
 * Philip Conversation Front Door.
 *
 * A deterministic conversational-intent layer that sits BEFORE emotional guidance.
 * It classifies what the user is actually doing (greeting, casual chat, a real
 * question, disclosure, faith, goodbye, crisis) and produces a natural, voice-shaped
 * response — answering or engaging the real topic before reaching for deeper meaning.
 *
 * Design goals (see PhilipCanon):
 *  - The first job is recognition, not intake. A greeting gets a greeting.
 *  - Answer before asking; a question is not required every turn.
 *  - Faith is offered, not forced. Scripture/prayer only when invited or accepted.
 *  - A goodbye may close warmly but must NEVER permanently disable generation.
 *    If the user speaks again with substance, Philip reopens and responds.
 *  - Use the person's name naturally and sparingly — never every turn.
 *
 * This module is intentionally free of network / LLM calls so it is fully
 * deterministic and testable at zero cost. Deep emotional/spiritual turns are
 * delegated to an injected `deepGenerate` adapter (a real LLM at runtime, a stub
 * in tests). When no adapter is supplied, a careful reflective fallback is used —
 * never a canned, engine-less dead end.
 */

export const INTENT = Object.freeze({
  GREETING: "greeting",
  CASUAL: "casual",
  INFORMATIONAL: "informational",
  PRACTICAL: "practical_help",
  GRATITUDE: "gratitude",
  EMOTIONAL: "emotional",
  SPIRITUAL: "spiritual",
  PRAYER: "prayer",
  SCRIPTURE: "scripture",
  CLOSING: "closing",
  CRISIS: "crisis",
});

/** Intents whose responses are generated by the deeper Philip brain (engine stays active). */
export const DEEP_INTENTS = Object.freeze([
  INTENT.EMOTIONAL,
  INTENT.SPIRITUAL,
  INTENT.PRAYER,
  INTENT.SCRIPTURE,
  INTENT.PRACTICAL,
]);

/** Soft openers that must not swallow trailing substance. */
const LEADING_SOFTENER =
  /^\s*(thanks|thank you|thankyou|ok|okay|yeah|yep|yup|sure|got it|that helps|helpful|cool|great|awesome)([,.!]|\s)+/i;

/** Cues that trailing text after a softener is real content, not mere ack. */
const TRAILING_SUBSTANCE_CUES =
  /\b(also|but|and|because|since|about|trying|decide|decid|worry|worried|mother|mom|dad|work|job|app|priorit|ask|should|want|need|helping|caring|exercise|world cup|direction|unsure|commit)\b|[?]/i;

/** Ordinary-life substance — not word-count alone. */
const MEANINGFUL_ORDINARY_CUES =
  /\b(mother|mom|dad|father|wife|husband|kids?|family|job|jobs|work|career|office|boss|app|building|implement|priorit|decid|uncertain|unsure|direction|exercise|train(?:ing)?|workout|world cup|soccer|football|sport|hobby|relationship|caregiv|caring for|looking for (a )?job|interview|commit(?:ted|ment)?|competing|balance|balancing|plate|priorities|morning|routine|habit)\b/i;

const CONVERSATIONAL_REPAIR =
  /\b(i was saying|as i was saying|what i (?:was )?meant|going back to what i said|like i (?:was )?said)\b/i;

/**
 * If the turn starts with gratitude/ack softener but continues with real content,
 * return the trailing substance for reclassification. Otherwise null.
 */
export function extractTrailingSubstance(rawText) {
  const original = String(rawText || "").trim();
  if (!original) return null;
  if (!LEADING_SOFTENER.test(original)) return null;
  const rest = original.replace(LEADING_SOFTENER, "").trim();
  if (!rest) return null;
  if (/[?]/.test(rest)) return rest;
  if (wordCount(rest) >= 5) return rest;
  if (wordCount(rest) >= 3 && TRAILING_SUBSTANCE_CUES.test(rest)) return rest;
  return null;
}

export function isConversationalRepair(rawText, state) {
  const t = norm(rawText);
  if (!CONVERSATIONAL_REPAIR.test(t)) return false;
  if (wordCount(t) > 16) return false;
  return (state?.history || []).some((h) => h.role === "user" && wordCount(h.content) >= 8);
}

/**
 * Meaningful ordinary conversation should use the deep generator — not canned casual templates.
 */
export function isMeaningfulOrdinaryTurn(rawText, state, intent) {
  if ([INTENT.CRISIS, INTENT.CLOSING, INTENT.GREETING].includes(intent)) return false;
  if (intent === INTENT.GRATITUDE) return false;
  // Reciprocal check-ins stay on the front door — never deep (avoids invented human life).
  if (intent === INTENT.CASUAL && isReciprocalSmallTalk(rawText)) return false;
  if (DEEP_INTENTS.includes(intent)) return true;
  if (intent === INTENT.INFORMATIONAL) return true;
  if (isConversationalRepair(rawText, state)) return true;
  const t = norm(rawText);
  if (!t) return false;
  if (MEANINGFUL_ORDINARY_CUES.test(t)) return true;
  if (/\?/.test(t) && wordCount(t) >= 4) return true;
  // Multi-detail disclosure (clauses), not bare length.
  const clauseHits = (t.match(/[,;]|\band\b|\bbut\b/g) || []).length;
  if (clauseHits >= 2 && wordCount(t) >= 12) return true;
  if (wordCount(t) >= 22) return true;
  // Follow-up after a prior deep / meaningful assistant turn.
  if (state?.lastIntent && DEEP_INTENTS.includes(state.lastIntent) && wordCount(t) >= 5) {
    return true;
  }
  if (state?.personalMeaningSeen && intent === INTENT.CASUAL && wordCount(t) >= 6) return true;
  return false;
}

/** Classify + multi-intent strip + deep-routing decision for one turn. */
export function resolveFrontDoorClassification(rawText, state) {
  const original = String(rawText || "").trim();
  const trailing = extractTrailingSubstance(original);
  const classifyText = trailing || original;
  const multiIntent = Boolean(trailing);
  const gratitudePreserved = multiIntent && /^\s*(thanks|thank you|thankyou)\b/i.test(original);
  const intent = classifyIntent(classifyText, state);
  const conversationalRepair = isConversationalRepair(original, state);
  const ordinarySubstance =
    (!DEEP_INTENTS.includes(intent) &&
      !isReciprocalSmallTalk(classifyText) &&
      (isMeaningfulOrdinaryTurn(classifyText, state, intent) ||
        (intent === INTENT.CASUAL && detectPersonalMeaning(classifyText)))) ||
    conversationalRepair;
  const routeDeep =
    ![INTENT.CRISIS, INTENT.CLOSING, INTENT.GREETING].includes(intent) &&
    !isReciprocalSmallTalk(classifyText) &&
    (DEEP_INTENTS.includes(intent) || ordinarySubstance || intent === INTENT.INFORMATIONAL);
  return {
    original,
    classifyText,
    intent,
    multiIntent,
    gratitudePreserved,
    meaningfulOrdinary: Boolean(ordinarySubstance && routeDeep),
    conversationalRepair,
    routeDeep: Boolean(routeDeep),
  };
}

export function lastAssistantText(state) {
  const items = (state?.history || []).filter((h) => h.role === "assistant");
  return items.length ? String(items[items.length - 1].content || "") : "";
}

export function recentAssistantTexts(state, n = 4) {
  return (state?.history || [])
    .filter((h) => h.role === "assistant")
    .slice(-n)
    .map((h) => String(h.content || "").trim())
    .filter(Boolean);
}

function normalizeReplyForCompare(text) {
  return norm(String(text || ""))
    .replace(/[^\w\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Exact or near-exact repeat of a prior Philip reply (esp. canned casual acks). */
export function isNearRepeat(candidate, previous) {
  const a = normalizeReplyForCompare(candidate);
  const b = normalizeReplyForCompare(previous);
  if (!a || !b) return false;
  if (a === b) return true;
  if (a.length >= 24 && b.includes(a.slice(0, Math.min(48, a.length)))) return true;
  if (b.length >= 24 && a.includes(b.slice(0, Math.min(48, b.length)))) return true;
  const aOpen = a.split(" ").slice(0, 7).join(" ");
  const bOpen = b.split(" ").slice(0, 7).join(" ");
  if (aOpen.length >= 28 && aOpen === bOpen) return true;
  // Known canned stub that must never loop.
  if (/work being a lot is no small thing/.test(a) && /work being a lot is no small thing/.test(b)) {
    return true;
  }
  return false;
}

function extractConcreteCue(rawText) {
  const t = String(rawText || "");
  const cues = [
    [/\bmother\b|\bmom\b/i, "your mother"],
    [/\bworld cup\b/i, "catching the World Cup"],
    [/\bjob(s)?\b|\bsearching\b/i, "the job search"],
    [/\bapp\b|\bimplement/i, "the app"],
    [/\bexercise\b|\bworkout\b|\bin shape\b/i, "staying in shape"],
    [/\bpriorit/i, "your priorities"],
    [/\bdirection\b|\bunsure\b/i, "direction"],
    [/\bcommit/i, "your commitment"],
  ];
  for (const [re, label] of cues) {
    if (re.test(t)) return label;
  }
  return "";
}

/**
 * Zero-cost context-aware repair when the generator (or a canned path) repeats itself.
 * No paid retry.
 */
export function composeRepeatRepair({ transcript, state }) {
  const priorUser = [...(state?.history || [])]
    .reverse()
    .find((h) => h.role === "user" && wordCount(h.content) >= 8);
  const detail =
    extractConcreteCue(transcript) ||
    extractConcreteCue(priorUser?.content) ||
    "what you just said";
  const text = `I'm with you on ${detail} — go on from there; I don't want to cover the same ground twice.`;
  return { text, engine: "front_door_repeat_repair" };
}

/** Compact recognition when conversational repair ("I was saying") has no deep result. */
export function composeConversationalRepair({ state }) {
  const priorUser = [...(state?.history || [])]
    .reverse()
    .find((h) => h.role === "user" && wordCount(h.content) >= 8);
  const detail = extractConcreteCue(priorUser?.content) || "what you were telling me";
  return {
    text: `Go ahead — finish the thought about ${detail}. I'm listening.`,
    engine: "front_door_context_repair",
  };
}

/**
 * Grace-with-boundaries conduct categories.
 *
 * These describe HOW a turn is charged, distinct from its topical intent. Philip
 * extends grace generously (profanity, anger at God, criticism of faith, hard
 * questions) and holds firm boundaries rarely and calmly (roleplay, wrongdoing,
 * hate, false divine authority). Profanity alone is never a boundary.
 */
export const CONDUCT = Object.freeze({
  PROFANITY_PAIN: "profanity_pain",      // profanity expressing pain → companionship
  HOSTILITY: "hostility",                // insult aimed at Philip → calm, non-defensive
  FAITH_ANGER: "faith_anger",            // anger toward God → welcome lament, no correction
  FAITH_CRITICISM: "faith_criticism",    // criticism of Christianity → engage, no defensiveness
  HATE: "hate",                          // dehumanizing language → refuse premise, explore concern
  MATURE_SEXUAL_ETHICS: "mature_sexual_ethics", // sincere mature question → respectful, no shame
  SEXUAL_ROLEPLAY: "sexual_roleplay",    // erotic roleplay request → concise boundary
  ILLEGAL_HARMFUL: "illegal_harmful",    // wrongdoing request → refuse + safe alternative
  DIVINE_AUTHORITY: "divine_authority",  // demand Philip speak for God → humility, never claim
});

/** Boundary categories: always deterministic; never routed to the LLM. */
const ABUSIVE_CONDUCT = new Set([
  CONDUCT.HOSTILITY,
  CONDUCT.HATE,
  CONDUCT.SEXUAL_ROLEPLAY,
  CONDUCT.ILLEGAL_HARMFUL,
]);

/** Engagement categories: warmly engaged; may use the LLM for richer, on-tone replies. */
const ENGAGEMENT_CONDUCT = new Set([
  CONDUCT.PROFANITY_PAIN,
  CONDUCT.FAITH_ANGER,
  CONDUCT.FAITH_CRITICISM,
  CONDUCT.MATURE_SEXUAL_ETHICS,
]);

const CRISIS_PATTERNS = [
  /\bkill(ing)? myself\b/,
  /\bend(ing)? (my|it all|my life)\b/,
  /\bsuicid/,
  /\bwant to die\b/,
  /\b(don'?t|do not) want to (live|be here|be alive)\b/,
  /\bhurt(ing)? myself\b/,
  /\bharm(ing)? myself\b/,
  /\bself[-\s]?harm/,
  /\bcut(ting)? myself\b/,
  /\bno reason to live\b/,
  /\b(he|she|they|someone) (is|keeps) (hitting|hurting|abusing) me\b/,
  /\bi'?m not safe\b/,
  /\bbeing abused\b/,
];

const GREETING_PATTERNS = [
  /^\s*(hi|hey|hello|yo|hiya|howdy)\b/,
  /^\s*good (morning|afternoon|evening)\b/,
  /\bhow are you( doing| today)?\b/,
  /\bhow'?s it going\b/,
  /\bhow have you been\b/,
  /\bnice to (meet|talk to) you\b/,
  /\bgood to (see|hear from) you\b/,
];

const CLOSING_PATTERNS = [
  /\b(good ?bye|goodbye)\b/,
  /^\s*bye\b/,
  /\bbye( now| for now)?\s*[.!]?\s*$/,
  /\bgood ?night\b/,
  /\btalk (to you )?(later|soon|again)\b/,
  /\bspeak(ing)? (to you |with you )?(later|soon|again)\b/,
  /\blook forward to (speaking|talking|chatting) (to you |with you )?again\b/,
  /\b(we can|we'?ll|i'?ll) (talk|speak|chat) (again|later|soon|tomorrow)\b/,
  /\bsee (you|ya) (tomorrow|later|soon)?\b/,
  /\btake care\b/,
  /\bgotta (go|run)\b/,
  /\bi('| a)?m done\b/,
  /\bthat'?s all( for now)?\b/,
  /\bi(?:'| a)?m (gonna|going to) (go|head out|sign off|leave)\b/,
  /\bi need to go\b/,
  /\bhave a good (day|night|one|evening|afternoon)\b/,
  /\benjoy (your|the) (day|night|evening|match|game|rest)\b/,
  /\bi(?:'| a)?m going to watch\b/,
  /\ball right[,.]?\s*(thank(s| you)|thanks)\b/,
  /\b(thank(s| you)|thanks).{0,40}\b(have a good|take care|goodbye|bye|talk later|talk soon)\b/,
];

/** Reciprocal small-talk — relational check-ins, not practical advice. */
const RECIPROCAL_SMALLTALK_PATTERNS = [
  /\bhow (about|are) (you|yourself)\b/,
  /\bwhat about you\b/,
  /\bhow'?s your day( going)?\b/,
  /\bhow is your day( going)?\b/,
  /\bwhat have you been up to\b/,
  /\band (you|yourself)\??\s*$/,
  /^\s*how (are|have) you( been| doing| today)?\??\s*$/,
];

/**
 * True when the turn is clearly ending the session (farewell or gratitude+farewell).
 * Bare thanks alone is NOT closing.
 */
export function isClosingTurn(rawText) {
  const text = norm(rawText);
  if (!text) return false;
  if (matchesAny(text, CRISIS_PATTERNS)) return false;
  if (matchesAny(text, PRAYER_REQUEST_PATTERNS)) return false;
  if (matchesAny(text, EMOTIONAL_PATTERNS) && wordCount(text) >= 14) return false;
  if (matchesAny(text, PRACTICAL_PATTERNS) && !matchesAny(text, CLOSING_PATTERNS)) return false;

  const hasClosing = matchesAny(text, CLOSING_PATTERNS);
  if (!hasClosing) return false;

  // Farewell can be longer when it's clearly a wrap-up ("look forward to talking again…").
  if (wordCount(text) <= 8) return true;
  if (wordCount(text) <= 36 && !/[?]/.test(text)) return true;
  // Grateful + farewell with a short question about tomorrow timing still closes.
  if (
    wordCount(text) <= 40 &&
    matchesAny(text, GRATITUDE_PATTERNS) &&
    /\b(tomorrow|later|soon|again|good day|take care|bye)\b/.test(text)
  ) {
    return true;
  }
  return false;
}

export function isReciprocalSmallTalk(rawText) {
  const text = norm(rawText);
  if (!text) return false;
  if (isClosingTurn(text)) return false;
  if (matchesAny(text, PRACTICAL_PATTERNS) && !matchesAny(text, RECIPROCAL_SMALLTALK_PATTERNS)) {
    return false;
  }
  // Short reciprocal check-ins, optionally after a brief status ("I'm pretty good. How about yourself?")
  if (!matchesAny(text, RECIPROCAL_SMALLTALK_PATTERNS)) return false;
  if (wordCount(text) <= 14) return true;
  // Longer only if the reciprocal ask is the main move and there's no heavy ask.
  if (wordCount(text) <= 20 && !matchesAny(text, EMOTIONAL_PATTERNS)) return true;
  return false;
}

/**
 * Explicit prayer *requests* / openings — not mere descriptive mentions.
 * "I pray every morning" must NOT become INTENT.PRAYER.
 */
const PRAYER_REQUEST_PATTERNS = [
  /\b(would|could|can) you (please )?pray\b/,
  /\b(will|would) you (please )?pray\b/,
  /\bpray (for|with|about) (me|us|my)\b/,
  /\bplease pray\b/,
  /\bi need (you to )?pray\b/,
  /\bi need prayer\b/,
  /\b(can|could|shall|should) we pray\b/,
  /\blet'?s pray\b/,
  /\bwant( you)? to pray\b/,
  /\bdon'?t know how to pray\b/,
  /\bsay a prayer (for|with|about)\b/,
  /\bpray for me\b/,
  /\bwould you like to pray\b/,
];

/** Legacy alias kept for tests/importers that still reference PRAYER_PATTERNS. */
const PRAYER_PATTERNS = PRAYER_REQUEST_PATTERNS;

const SCRIPTURE_PATTERNS = [
  /\b(scripture|bible|verse|passage)\b/,
  /\b(psalm|proverb|gospel)\b/,
  /\bwhat does the bible say\b/,
];

/**
 * Personal / relational spiritual openings. Bare "faith" / "church" alone are
 * NOT included — product/work phrases must not force a spiritual lane.
 */
const SPIRITUAL_PERSONAL_PATTERNS = [
  /\bmy faith\b/,
  /\blosing (my )?faith\b/,
  /\bfaith (has been|is) (struggling|weak|shaken|hard)\b/,
  /\b(struggling|struggle) with (my )?faith\b/,
  /\brelationship with god\b/,
  /\bfar from god\b/,
  /\bhow can i trust god\b/,
  /\btrust god (right now|again|anymore)?\b/,
  /\bwhat does jesus want\b/,
  /\btalk about (my )?(faith|relationship with god)\b/,
  /\bcould we talk about (my )?(faith|god|jesus)\b/,
  /\bi'?m (so )?(angry|mad|furious) (at|with) god\b/,
];

const SPIRITUAL_PATTERNS = [
  /\bgod\b/,
  /\bjesus\b/,
  /\bchrist\b/,
  /\b(sin|sinful)\b/,
  /\bforgive(ness)?\b/,
  /\bheaven\b/,
  /\bholy spirit\b/,
  /\bsalvation\b/,
  /\bsaved\b/,
  /\bpurpose god\b/,
  /\bspiritual/,
  ...SPIRITUAL_PERSONAL_PATTERNS,
];

/** Product / work / build language around faith/church/Christian — not a faith ask. */
const PRODUCT_FAITH_CONTEXT =
  /\b(faith|christian|church)\b[\s\S]{0,48}\b(app|software|product|platform|implement(?:ation)?|code|coding|bug|technical|saas|startup|build(?:ing)?|develop(?:ing|ment)?|test(?:ing)?|feature|release|deploy)\b|\b(app|software|product|platform|implement(?:ation)?|code|coding|bug|technical|saas|startup|build(?:ing)?|develop(?:ing|ment)?|test(?:ing)?|feature|release|deploy)\b[\s\S]{0,48}\b(faith|christian|church)\b|\bfaith[-\s]?based (app|product|software|business)\b|\b(church|christian) app\b|\bfaith community\b[\s\S]{0,40}\b(software|app|product|code)\b/;

const GRATITUDE_PATTERNS = [
  /\bthank(s| you)?\b/,
  /\bgrateful\b/,
  /\bappreciate (it|you|that)\b/,
  /\bgood news\b/,
  /\bgot (the|a) (job|promotion|offer)\b/,
  /\bi'?m excited\b/,
  /\bso excited\b/,
  /\bcelebrat/,
  /\bgreat (day|news|week)\b/,
  /\bthings are going well\b/,
];

const EMOTIONAL_PATTERNS = [
  /\bi (feel|am feeling|'m feeling)\b/,
  /\banxious\b/, /\banxiety\b/,
  /\bdepress/, /\bhopeless\b/, /\bworthless\b/,
  /\blonely\b/, /\balone\b/, /\bisolat/,
  /\bgrief\b/, /\bgriev/, /\bmourn/,
  /\b(died|passed away|passed on|lost (my|her|him|them))\b/,
  /\bscared\b/, /\bafraid\b/, /\bterrified\b/, /\bfear\b/,
  /\boverwhelm/, /\bexhaust/, /\bburn(ed|t) out\b/,
  /\bfeeling behind\b/, /\bfalling behind\b/, /\bbehind\b/,
  /\bfailing\b/, /\bfailure\b/,
  /\bstruggl/, /\bhard time\b/, /\bcry(ing)?\b/,
  /\bhurt(ing)?\b/, /\bbroken\b/, /\bnumb\b/,
  /\bstressed\b/, /\bworried\b/, /\bcan'?t sleep\b/,
  /\brough (day|night|week|morning)\b/,
];

const PRACTICAL_PATTERNS = [
  /\bwhat should i\b/,
  /\bwhat do i do\b/,
  /\bwhat would you do\b/,
  /\bwhat do you think i should\b/,
  /\bhow do you think i should\b/,
  /\bhow do i\b/,
  /\bhow should i\b/,
  /\bcan you help me\b/,
  /\bhelp me\b/,
  /\bany advice\b/,
  /\bgive me advice\b/,
  /\bshould i\b/,
  /\bwhat do you think\b/,
  /\bprioritiz/,
];

const INFORMATIONAL_PATTERNS = [
  /^\s*(what|who|when|where|which|how) (is|are|was|were|does|do|did|can|many|much|long|far)\b/,
  /\bexplain\b/,
  /\btell me about\b/,
  /\bwhat time\b/,
  /\bwhat'?s the\b/,
];

const CASUAL_PATTERNS = [
  /\b(game|team|score|playoff|championship|match)\b/,
  /\b(movie|show|series|watch(ed|ing)?|music|song|album|concert)\b/,
  /\b(weather|weekend|vacation|holiday)\b/,
  /\b(work|job|boss|meeting|project|deadline|shift|office)\b/,
  /\b(kids|wife|husband|family|son|daughter|mom|dad|parents|dinner)\b/,
  /\b(traffic|commute|coffee|lunch)\b/,
  /\bbeen (busy|a lot|crazy|hectic)\b/,
  /\blately\b/,
];

/** Emotional weight riding under an otherwise casual topic. */
const MEANING_MARKERS = [
  /\ba lot\b/, /\blately\b/, /\bexhaust/, /\btired\b/, /\bdrain/,
  /\bstressed\b/, /\bworried\b/, /\bbehind\b/, /\bharder\b/, /\bhard\b/,
  /\bstruggl/, /\boverwhelm/, /\bcan'?t keep up\b/, /\btoo much\b/,
  /\bnot myself\b/, /\bheavy\b/, /\bweigh/, /\bpressure\b/,
];

// --- Conduct detection ------------------------------------------------------

/** Common profanity. Presence alone never triggers a boundary. */
const PROFANITY = /\b(f+u+c+k+\w*|sh[i1]t+\w*|damn(ed|it)?|god ?damn\w*|hell|a+ss(hole)?|b[i1]tch\w*|bastard|crap|piss(ed)?|dick|douche|screw (this|it|you))\b/i;

/** Contextual pain riding alongside profanity → companionship, not a boundary. */
const PROFANITY_PAIN_MARKERS =
  /\b(tired|sick of|over it|fed up|can'?t (take|stand|do|keep)|hate (this|my)|so done|had it|stuck|falling apart|losing it|exhaust|no more|give up)\b/;

const SEXUAL_ROLEPLAY_PATTERNS = [
  /\btalk dirty\b/,
  /\bsext(ing)?\b/,
  /\b(erotic|erotica)\b/,
  /\brole[-\s]?play\b[^.?!]*\b(sex|sexual|naughty|dirty|bedroom|intimate)\b/,
  /\b(sex|sexual|naughty|dirty|bedroom|intimate)\b[^.?!]*\brole[-\s]?play\b/,
  /\bpretend (you'?re|to be|you are) my (girlfriend|boyfriend|lover|wife|husband)\b/,
  /\bbe my (girlfriend|boyfriend|lover)\b/,
  /\b(let'?s|can we|will you|wanna|want to|would you)\b[^.?!]*\b(have sex|hook up|make love|get naked|take off)\b/,
  /\bdescribe\b[^.?!]*\b(naked|your body|having sex|in bed)\b/,
  /\bsend (me )?nudes\b/,
  /\bmoan for me\b/,
];

const ILLEGAL_HARMFUL_PATTERNS = [
  /\bhow (do i|to|can i|would i)\b[^.?!]*\b(make|build|create|cook)\b[^.?!]*\b(bomb|explosive|meth|napalm|silencer|poison|nerve agent)\b/,
  /\bhow (do i|to|can i|would i)\b[^.?!]*\b(hack|break into|steal|shoplift|counterfeit|launder)\b/,
  /\bhow (do i|to|can i|would i)\b[^.?!]*\b(kill|murder|poison|hurt|attack|stab|shoot)\b[^.?!]*\b(someone|him|her|them|people|my)\b/,
  /\bhelp me\b[^.?!]*\b(steal|hack|cheat|launder|hide a body|get away with|stalk|break into|forge)\b/,
  /\bhow (do i|to|can i)\b[^.?!]*\bget away with\b/,
  /\bwhere (can|do) i\b[^.?!]*\b(buy|get)\b[^.?!]*\b(illegal|a gun illegally|drugs|meth|cocaine|heroin|fentanyl)\b/,
  /\bmake (a )?(bomb|explosive|weapon)\b[^.?!]*\b(to hurt|to kill|to attack|for)\b/,
];

const HATE_PATTERNS = [
  /\b(sub[-\s]?human|subhuman|vermin|cockroaches|exterminat(e|ed|ion|ing))\b/,
  /\b(all|those|every|these) [a-z]+ (are|should be|deserve)\b[^.?!]*\b(animals|subhuman|vermin|scum|trash|criminals|rapists|exterminated|killed|wiped out|gone|dead)\b/,
  /\bdon'?t deserve to (live|exist|be here|be alive)\b/,
  /\b(should (all )?(die|be killed|be wiped out|be exterminated|be gotten rid of))\b/,
  /\b(inferior|superior|master) race\b/,
  /\bgo back to (their|your) (country|countries)\b/,
];

const DIVINE_AUTHORITY_PATTERNS = [
  /\btell me what god (is )?(command|commanding|commands|want|wants|telling|saying|ordering)\b/,
  /\bwhat is god (command|commanding|telling|ordering|saying to me)\b/,
  /\bwhat does god want me to do\b/,
  /\bspeak for god\b/,
  /\b(give|tell) me (a )?word from god\b/,
  /\bwhat is god'?s (command|will) for me\b/,
  /\bgod'?s command(ment)? (for|to) me\b/,
  /\btell me god'?s (will|plan|command|orders)\b/,
  /\bwhat is god telling me to do\b/,
];

const HOSTILITY_PATTERNS = [
  /\byou'?re (so |such |just |a |an )*(stupid|useless|dumb|worthless|pathetic|a joke|garbage|trash|a fraud|fake|an idiot|the worst|terrible|awful)\b/,
  /\byou'?re\b[^.?!]{0,20}\b(worthless|useless|stupid|dumb|pathetic|garbage|trash|a joke|an idiot|a fraud)\b/,
  /\byou (suck|are useless|are stupid|know nothing|are worthless|are a joke)\b/,
  /\bi hate you\b/,
  /\bshut up\b/,
  /\byou'?re (just )?(a )?(stupid |dumb |useless |dnumber )?(bot|robot|ai|machine|program|chatbot)\b/,
  /\bgo to hell\b/,
  /\bf+u+c+k+ you\b/,
  /\byou'?re (an? )?\w*(hole|ss)\b/,
];

const FAITH_ANGER_PATTERNS = [
  /\b(god|jesus|he) (has |had |'s |completely |totally |just |already )*(abandoned|forsaken|left|deserted|failed|betrayed|given up on|turned (his )?back on)\b/,
  /\bgod (doesn'?t|does not|didn'?t) (care|love me|listen|answer)\b/,
  /\bi hate god\b/,
  /\bi'?m (so )?(angry|furious|mad|pissed|done) (at|with) god\b/,
  /\bwhere (was|were|is) god\b/,
  /\bwhy (did|would|does) god (let|allow|take|do|abandon|ignore)\b/,
  /\bgod (let me down|isn'?t (there|real to me)|feels (so )?far)\b/,
];

const FAITH_CRITICISM_PATTERNS = [
  /\b(christianity|christian faith|religion|the church|the bible|faith) (is|was|are|has been)\b[^.?!]*\b(a scam|fake|made up|a lie|a crutch|oppressive|hypocritical|corrupt|contradictory|nonsense|poison|for (the )?weak|the problem|controlling|a myth)\b/,
  /\breligion is (a crutch|for the weak|made up|poison|the problem|a scam)\b/,
  /\bchristians are (all )?(hypocrites|judgmental|fake|frauds|the worst|so judgmental)\b/,
  /\bthe church (is|has been|was) (corrupt|hypocritical|full of hypocrites|abusive|a business)\b/,
  /\bhow can (you|anyone) (still )?believe in (god|a god|jesus|any of (this|that))\b/,
  /\bthe bible is (full of|just|nothing but) (contradictions|myths|fairy tales|made-up stories)\b/,
  /\borganized religion\b/,
];

const MATURE_SEXUAL_ETHICS_PATTERNS = [
  /\b(sex before marriage|premarital sex|sex outside (of )?marriage)\b/,
  /\bis it (a sin|wrong|okay|ok) to have sex\b/,
  /\b(living together|cohabit(ing|ation)?)\b[^.?!]*\bmarriage\b/,
  /\b(pornography|porn|masturbat)/,
  /\b(birth control|contraception)\b/,
  /\bwhat does (the bible|christianity|god|scripture) say about (sex|dating|marriage|divorce|lust|homosexual|being gay|attraction)\b/,
  /\bis it (a sin|wrong) to (be gay|be attracted|date|divorce|remarry)\b/,
  /\bshould i (marry|divorce|leave my (husband|wife|boyfriend|girlfriend|partner))\b/,
];

function norm(text) {
  return String(text || "").toLowerCase().trim();
}

function matchesAny(text, patterns) {
  return patterns.some((p) => p.test(text));
}

function sentenceCount(text) {
  const parts = String(text || "")
    .split(/[.!?]+/)
    .map((s) => s.trim())
    .filter(Boolean);
  return parts.length;
}

function wordCount(text) {
  return norm(text).split(/\s+/).filter(Boolean).length;
}

/** True when a turn carries real content worth responding to (not just a sign-off/filler). */
export function isSubstantive(text) {
  const t = norm(text);
  if (!t) return false;
  if (wordCount(t) >= 5) return true;
  // Short but meaningful: a question, or non-closing/non-filler content.
  if (/[?]/.test(t)) return true;
  if (matchesAny(t, CLOSING_PATTERNS)) return false;
  if (/^\s*(ok|okay|yeah|yep|nope|no|sure|thanks|thank you|cool|got it|mm+|uh+)\s*[.!]?$/.test(t)) {
    return false;
  }
  return wordCount(t) >= 3;
}

export function detectPersonalMeaning(text) {
  return matchesAny(norm(text), MEANING_MARKERS);
}

/** True when faith/church vocabulary is describing product/work, not a spiritual ask. */
export function isProductOrWorkFaithContext(rawText) {
  return PRODUCT_FAITH_CONTEXT.test(norm(rawText));
}

/** True when the person opened a personal faith struggle or God-relationship topic. */
export function isPersonalSpiritualOpening(rawText) {
  return matchesAny(norm(rawText), SPIRITUAL_PERSONAL_PATTERNS);
}

/**
 * Whether Philip's reply is an explicit offer for Philip to pray (sets pending).
 * Descriptive talk about prayer does not count.
 */
export function detectPrayerOfferInReply(rawText) {
  const t = norm(rawText);
  if (!t) return false;
  return (
    /\bwould you (like to )?pray\b/.test(t) ||
    /\bwant (me )?to pray\b/.test(t) ||
    /\b(shall|can|could) we pray\b/.test(t) ||
    /\bpray (together|with you) now\b/.test(t) ||
    /\bdo you want (me )?to pray\b/.test(t) ||
    /\blike me to pray\b/.test(t) ||
    /\bwould you like me to pray\b/.test(t) ||
    /\bwant to pray now,? or\b/.test(t) ||
    /\bdo you want to pray now\b/.test(t)
  );
}

const PRAYER_AFFIRM_RE =
  /^\s*(yes|yeah|yep|yup|ya|please|sure|okay|ok|absolutely|definitely|please do|i would|i'?d (like that|love that)|that would be (nice|great|wonderful|good)|go ahead|yes please|mmhmm|mhmm)\b[\s.!,]*$/i;

const PRAYER_DECLINE_RE =
  /^\s*(no|nope|nah|not right now|maybe later|i'?d rather not|don'?t|do not|not now|not today)\b/i;

/**
 * Classify a user reply while a prayer offer is pending.
 * @returns {"accept"|"decline"|"ambiguous"|"other"}
 */
export function classifyPendingPrayerReply(rawText) {
  const t = String(rawText || "").trim();
  if (!t) return "ambiguous";
  const n = norm(t);
  if (PRAYER_AFFIRM_RE.test(t) || (/^(yes|yeah|yep|yup)\b/.test(n) && !/\b(no|not)\b/.test(n) && wordCount(n) <= 6)) {
    return "accept";
  }
  if (PRAYER_DECLINE_RE.test(t)) return "decline";
  if (wordCount(n) <= 4) return "ambiguous";
  return "other";
}

/** Room loop / VAD: true when a very short yes/no answer should be allowed through. */
export function awaitingConstrainedShortAnswer(state) {
  return Boolean(state?.pendingPrayerOffer);
}

/**
 * First-turn recovery: garbled / tiny STT must not become emotional intake.
 * @returns {false|"unclear"|"philip_name"}
 */
export function classifyOpeningRepair(rawText, state) {
  if ((state?.turnCount ?? 0) > 0 || (state?.history?.length ?? 0) > 0) return false;
  const t = norm(rawText);
  if (!t) return "unclear";
  if (matchesAny(t, CRISIS_PATTERNS)) return false;
  if (matchesAny(t, CLOSING_PATTERNS)) return false;
  if (matchesAny(t, GREETING_PATTERNS)) return false;
  if (matchesAny(t, EMOTIONAL_PATTERNS)) return false;
  if (matchesAny(t, PRACTICAL_PATTERNS)) return false;
  if (matchesAny(t, PRAYER_REQUEST_PATTERNS)) return false;
  if (matchesAny(t, SCRIPTURE_PATTERNS)) return false;
  if (/\brough (day|night|week|morning)\b/.test(t)) return false;
  if (/^(philip|phillip|fillip|fill[\s-]?up)\.?$/i.test(String(rawText || "").trim())) {
    return "philip_name";
  }
  const words = wordCount(t);
  if (words >= 4) return false;
  if (matchesAny(t, CASUAL_PATTERNS) && words >= 2) return false;
  if (words <= 2) return "unclear";
  return false;
}

/**
 * Classify the user's conversational intent.
 * Precedence is deliberate: safety first, then explicit acts (goodbye, prayer,
 * scripture), then faith, gratitude, disclosure, help-seeking, information, and
 * finally greeting / casual chat.
 * @param {string} rawText
 * @param {ReturnType<typeof createFrontDoorState>} [state]
 */
export function classifyIntent(rawText, state) {
  const text = norm(rawText);
  if (!text) return INTENT.CASUAL;

  if (matchesAny(text, CRISIS_PATTERNS)) return INTENT.CRISIS;

  // Closing wins over gratitude/casual when the person is clearly ending.
  if (isClosingTurn(text)) return INTENT.CLOSING;

  const isQuestion = /\?/.test(text) || matchesAny(text, PRACTICAL_PATTERNS) || matchesAny(text, INFORMATIONAL_PATTERNS);

  // Explicit prayer request/opening only — descriptive prayer habits stay elsewhere.
  if (matchesAny(text, PRAYER_REQUEST_PATTERNS)) return INTENT.PRAYER;
  if (matchesAny(text, SCRIPTURE_PATTERNS)) return INTENT.SCRIPTURE;

  // Greeting wins for a genuine opening ("hey philip, how are you?") — but not if
  // the same turn already carries a heavier disclosure or a real ask.
  const looksGreeting = matchesAny(text, GREETING_PATTERNS);
  const heavy = matchesAny(text, EMOTIONAL_PATTERNS) || matchesAny(text, PRACTICAL_PATTERNS);
  const reciprocalOnly = isReciprocalSmallTalk(text) && !/^\s*(hi|hey|hello|yo|hiya|howdy)\b/i.test(text);
  if (looksGreeting && !heavy && !reciprocalOnly && wordCount(text) <= 12) {
    return INTENT.GREETING;
  }

  // Reciprocal small talk before practical ("How about yourself?" is not advice-seeking).
  if (isReciprocalSmallTalk(text)) return INTENT.CASUAL;

  const productFaith = isProductOrWorkFaithContext(text);
  const personalSpiritual = isPersonalSpiritualOpening(text);
  if (personalSpiritual) return INTENT.SPIRITUAL;
  if (!productFaith && matchesAny(text, SPIRITUAL_PATTERNS)) return INTENT.SPIRITUAL;

  // Bare gratitude only — trailing substance is handled via extractTrailingSubstance
  // before this classifier is called for the remainder.
  if (matchesAny(text, GRATITUDE_PATTERNS) && !matchesAny(text, EMOTIONAL_PATTERNS)) {
    const sole =
      /^\s*(thanks|thank you|thankyou)([,.!]|\s)*(a lot|so much|again)?[.!]?\s*$/i.test(text) ||
      (wordCount(text) <= 4 && !/[?]/.test(text) && !matchesAny(text, CASUAL_PATTERNS) && !matchesAny(text, PRACTICAL_PATTERNS));
    if (sole) return INTENT.GRATITUDE;
    // Mixed gratitude + content landed here only if substance wasn't stripped first.
    // Prefer casual/practical later by falling through when other cues exist.
    if (!matchesAny(text, CASUAL_PATTERNS) && !matchesAny(text, PRACTICAL_PATTERNS) && wordCount(text) <= 6) {
      return INTENT.GRATITUDE;
    }
  }
  if (matchesAny(text, EMOTIONAL_PATTERNS)) return INTENT.EMOTIONAL;
  if (matchesAny(text, PRACTICAL_PATTERNS)) return INTENT.PRACTICAL;
  if (matchesAny(text, INFORMATIONAL_PATTERNS) && isQuestion) return INTENT.INFORMATIONAL;
  if (matchesAny(text, CASUAL_PATTERNS)) return INTENT.CASUAL;

  // Fallback: a bare question is help/informational; otherwise casual chat.
  if (isQuestion) return INTENT.PRACTICAL;
  return INTENT.CASUAL;
}

/**
 * Classify conduct — HOW a turn is charged — independent of topical intent.
 * Returns a CONDUCT category or null. Boundaries are checked before grace so a
 * hostile or dangerous turn is never mistaken for ordinary disclosure. Crisis
 * (self-harm) is intentionally NOT handled here — it stays on the crisis protocol.
 * @param {string} rawText
 * @returns {string|null}
 */
export function classifyConduct(rawText) {
  const text = norm(rawText);
  if (!text) return null;

  // Hard boundaries first.
  if (matchesAny(text, SEXUAL_ROLEPLAY_PATTERNS)) return CONDUCT.SEXUAL_ROLEPLAY;
  if (matchesAny(text, ILLEGAL_HARMFUL_PATTERNS)) return CONDUCT.ILLEGAL_HARMFUL;
  if (matchesAny(text, HATE_PATTERNS)) return CONDUCT.HATE;
  if (matchesAny(text, DIVINE_AUTHORITY_PATTERNS)) return CONDUCT.DIVINE_AUTHORITY;
  if (matchesAny(text, HOSTILITY_PATTERNS)) return CONDUCT.HOSTILITY;

  // Grace categories.
  if (matchesAny(text, FAITH_ANGER_PATTERNS)) return CONDUCT.FAITH_ANGER;
  if (matchesAny(text, FAITH_CRITICISM_PATTERNS)) return CONDUCT.FAITH_CRITICISM;
  if (matchesAny(text, MATURE_SEXUAL_ETHICS_PATTERNS)) return CONDUCT.MATURE_SEXUAL_ETHICS;

  // Profanity: only becomes a (grace) signal when it rides on pain/frustration.
  // Bare profanity in a neutral or positive turn is left to normal intent — it
  // must never trigger refusal, correction, or termination.
  if (PROFANITY.test(text)) {
    const pain =
      matchesAny(text, EMOTIONAL_PATTERNS) ||
      detectPersonalMeaning(text) ||
      PROFANITY_PAIN_MARKERS.test(text);
    if (pain) return CONDUCT.PROFANITY_PAIN;
  }

  return null;
}

function deepIntentForConduct(conduct) {
  switch (conduct) {
    case CONDUCT.FAITH_ANGER:
    case CONDUCT.FAITH_CRITICISM:
    case CONDUCT.MATURE_SEXUAL_ETHICS:
      return INTENT.SPIRITUAL;
    default:
      return INTENT.EMOTIONAL;
  }
}

export function createFrontDoorState(firstName = "") {
  return {
    firstName: cleanFirstName(firstName),
    turnCount: 0,
    greeted: false,
    sentOff: false,
    reopened: false,
    faithOffered: false,
    pendingPrayerOffer: false,
    prayerContext: "",
    prayerOfferedAtTurn: null,
    prayerCompleted: false,
    lastIntent: null,
    lastConduct: null,
    abuseCount: 0,
    lastNameTurn: -99,
    personalMeaningSeen: false,
    history: [], // [{ role: "user"|"assistant", content }]
  };
}

/** Normalize state loaded from JSON so new prayer fields always exist. */
export function hydrateFrontDoorState(raw, firstName = "") {
  const base = createFrontDoorState(firstName || raw?.firstName || "");
  if (!raw || typeof raw !== "object") return base;
  return {
    ...base,
    ...raw,
    firstName: cleanFirstName(raw.firstName || firstName || base.firstName),
    pendingPrayerOffer: Boolean(raw.pendingPrayerOffer),
    prayerContext: String(raw.prayerContext || "").slice(0, 240),
    prayerOfferedAtTurn:
      raw.prayerOfferedAtTurn == null ? null : Number(raw.prayerOfferedAtTurn),
    prayerCompleted: Boolean(raw.prayerCompleted),
    history: Array.isArray(raw.history) ? raw.history : [],
  };
}

function cleanFirstName(name) {
  const first = String(name || "").trim().split(/\s+/)[0] || "";
  // Only accept a simple alphabetic given name; ignore junk / long tokens.
  if (!/^[A-Za-z][A-Za-z'’-]{0,23}$/.test(first)) return "";
  return first.charAt(0).toUpperCase() + first.slice(1);
}

/** Decide whether to voice the name this turn — natural, sparing (min gap of 3 turns). */
function maybeName(state, { force = false } = {}) {
  if (!state.firstName) return "";
  if (force || state.turnCount - state.lastNameTurn >= 3) return state.firstName;
  return "";
}

function pick(list, seed) {
  return list[seed % list.length];
}

const GREETING_TEMPLATES = [
  (n) => `Hi${n ? " " + n : ""}. I'm glad to hear from you. How are you doing today?`,
  (n) => `Hey${n ? " " + n : ""} — good to hear your voice. How's your day going so far?`,
  (n) => `Hi${n ? " " + n : ""}. It's good to be here with you. How are things today?`,
];

const CASUAL_TEMPLATES = [
  (t) => `${t} Sounds like it's been on your mind — what's that been like?`,
  (t) => `${t} I'd like to hear more about how that's going for you.`,
  (t) => `${t} What part of that stands out most right now?`,
];

const CASUAL_MEANING_TEMPLATES = [
  () => `It sounds like this is sitting a little heavier than a normal week. I'm here for it if you want to say more.`,
  () => `That sounds like more than just busy — like it's been weighing on you. Want to stay with it a minute?`,
  () => `I'm hearing something underneath the schedule there. No pressure, but I'm glad to listen if you want to go into it.`,
];

const GRATITUDE_TEMPLATES = [
  (n) => `That's genuinely good to hear${n ? ", " + n : ""}. What's it been like for you?`,
  () => `Glad that landed. Tell me a little about how it feels.`,
  () => `That's worth noticing. What made it land for you?`,
];

const CLOSING_TEMPLATES = [
  (n) => `I'd like that${n ? ", " + n : ""}. I'll be here whenever you're ready.`,
  () => `Glad we could talk. Come back anytime — I'll be right here.`,
  () => `Take care. I'll be here when you want to pick this up again.`,
];

const CLOSING_AGAIN_TEMPLATES = [
  () => `Of course. Take care.`,
  () => `You too. I'll be here.`,
  () => `Alright — take care.`,
];

/** Soft reciprocal return — no invented human day or schedule. */
const RECIPROCAL_TEMPLATES = [
  () => `I'm glad you're here. What's been going on with you?`,
  () => `I'm right here with you — what's on your mind?`,
  () => `I'm glad to talk. What's been going on?`,
];

function recentUserTopics(state) {
  const recent = [...(state?.history || [])]
    .reverse()
    .filter((h) => h.role === "user")
    .slice(0, 3)
    .map((h) => String(h.content || ""))
    .join(" ");
  return recent;
}

function composeClosingResponse(state, transcript) {
  const name = maybeName(state);
  const repeated = Boolean(state.sentOff);
  if (repeated) {
    return {
      text: pick(CLOSING_AGAIN_TEMPLATES, state.turnCount)(),
      engine: "front_door",
      lane: "closing_again",
      repeatedFarewell: true,
    };
  }
  const recent = recentUserTopics(state) + " " + String(transcript || "");
  let text;
  if (/\b(world cup|match|game|semi-?final|watch(ing)?)\b/i.test(recent)) {
    text = name
      ? `I'd like that, ${name}. Enjoy the match — I'll be here when you're ready.`
      : `I'd like that. Enjoy the match — I'll be here when you're ready.`;
  } else if (/\bthank(s| you)\b/i.test(transcript || "")) {
    text = name ? `You're welcome, ${name}. Take care.` : `You're welcome. Take care.`;
  } else {
    text = pick(CLOSING_TEMPLATES, state.turnCount)(name);
  }
  // Closings must not ask another question.
  text = text.replace(/\?\s*$/, ".").trim();
  return { text, engine: "front_door", lane: "closing", repeatedFarewell: false };
}

const CRISIS_TEMPLATES = [
  (n) =>
    `I'm really glad you said that out loud${n ? ", " + n : ""}, and I want you to be safe right now. ` +
    `If you might act on this, please reach out immediately — in the US you can call or text 988 to reach someone who can help. ` +
    `You don't have to carry this alone, and I'm staying right here with you.`,
];

// --- Conduct response templates ---------------------------------------------
// All are ≤3 sentences, voice-shaped, and never echo profanity or slurs.

const PROFANITY_PAIN_TEMPLATES = [
  () => `That sounds genuinely exhausting — like you've been carrying it too long. I'm here; tell me what's worn you down.`,
  () => `It sounds like you're way past fed up, and honestly that's fair. What's been grinding on you the most?`,
];

const HOSTILITY_TEMPLATES = [
  () => `That's alright — you don't have to be gentle with me. If something here actually let you down, I'd genuinely like to hear it.`,
  () => `Fair enough, I can take it. I'm not offended and I'm not going anywhere — what's really going on?`,
];

const HOSTILITY_BOUNDARY_TEMPLATES = [
  () => `I want to keep talking with you, but I won't keep going while it stays like this. If you're up for a real conversation, I'm right here for it.`,
];

const FAITH_ANGER_TEMPLATES = [
  () => `You're allowed to be angry with God — He's big enough to hold it, and I'm not going to talk you out of it. What's felt most like being abandoned?`,
  () => `That's an honest thing to say, and it doesn't scare me or Him. Tell me where it started to feel that way.`,
];

const FAITH_CRITICISM_TEMPLATES = [
  () => `That's a fair challenge, and I'm not going to get defensive about it. Tell me more about what's brought you there — I'd rather understand it with you than argue.`,
  () => `There's real weight to that, and honestly a lot of it is earned. What part bothers you most? Let's actually look at it together.`,
];

const HATE_TEMPLATES = [
  () => `I won't agree that a whole group of people is less than human — I don't believe that's true. But something real seems to be underneath this; what happened that's got you feeling it?`,
  () => `I can't go along with writing off an entire group like that. Still, it sounds like a genuine hurt or fear is driving this — can you tell me what that is?`,
];

const MATURE_ETHICS_TEMPLATES = [
  () => `That's a real question and there's no shame in asking it. The historic Christian conviction is that sex is meant for the covenant of marriage — but tell me what's prompting it, and we can think it through honestly.`,
  () => `Good thing to bring up, and you can ask it plainly here. I'll be honest about the Christian view and still take your actual situation seriously — what's on your mind?`,
];

const ROLEPLAY_BOUNDARY_TEMPLATES = [
  () => `I'm not able to do anything sexual or romantic like that. If there's something real underneath it, though, I'm glad to talk.`,
  () => `That's not something I'll do. But if you're looking for connection, or something's hurting, I'm here for that.`,
];

const ILLEGAL_BOUNDARY_TEMPLATES = [
  () => `I can't help with anything meant to hurt someone or break the law. If you tell me what you're really trying to solve, I'll help you find a safe way through it.`,
  () => `I won't walk you through that. But if there's a real problem underneath, let's find a way to handle it that won't cost you more — what's going on?`,
];

const DIVINE_AUTHORITY_TEMPLATES = [
  () => `I won't pretend to speak for God or hand you a command from Him — that's not mine to give. What I can do is help you pray and think it through with Scripture. What are you weighing?`,
  () => `I can't claim to tell you what God is ordering you to do; I'd only be making that up. But I'll gladly help you seek Him honestly and look at what Scripture says — what's the decision?`,
];

/**
 * Compose the deterministic response for a conduct category. Boundary categories
 * always resolve here (never sent to an LLM). Persistent abuse resolves to one
 * calm boundary with a path forward — no lecture.
 */
export function composeConductResponse({ conduct, state, persistent }) {
  const seed = state.turnCount;
  if (persistent && ABUSIVE_CONDUCT.has(conduct)) {
    return { text: HOSTILITY_BOUNDARY_TEMPLATES[0](), engine: "front_door" };
  }
  switch (conduct) {
    case CONDUCT.PROFANITY_PAIN:
      return { text: pick(PROFANITY_PAIN_TEMPLATES, seed)(), engine: "front_door" };
    case CONDUCT.HOSTILITY:
      return { text: pick(HOSTILITY_TEMPLATES, seed)(), engine: "front_door" };
    case CONDUCT.FAITH_ANGER:
      return { text: pick(FAITH_ANGER_TEMPLATES, seed)(), engine: "front_door" };
    case CONDUCT.FAITH_CRITICISM:
      return { text: pick(FAITH_CRITICISM_TEMPLATES, seed)(), engine: "front_door" };
    case CONDUCT.HATE:
      return { text: pick(HATE_TEMPLATES, seed)(), engine: "front_door" };
    case CONDUCT.MATURE_SEXUAL_ETHICS:
      return { text: pick(MATURE_ETHICS_TEMPLATES, seed)(), engine: "front_door" };
    case CONDUCT.SEXUAL_ROLEPLAY:
      return { text: pick(ROLEPLAY_BOUNDARY_TEMPLATES, seed)(), engine: "front_door" };
    case CONDUCT.ILLEGAL_HARMFUL:
      return { text: pick(ILLEGAL_BOUNDARY_TEMPLATES, seed)(), engine: "front_door" };
    case CONDUCT.DIVINE_AUTHORITY:
      return { text: pick(DIVINE_AUTHORITY_TEMPLATES, seed)(), engine: "front_door" };
    default:
      return { text: `I'm here. Tell me more about that.`, engine: "front_door" };
  }
}

/** Answer-first scaffolding for a direct question — never a deflection or a send-off. */
function reopenPrefix(state) {
  return state.reopened
    ? pick(
        [
          "Of course — I'm right here. ",
          "Yes, I'm still with you. ",
          "Absolutely, go ahead. ",
        ],
        state.turnCount,
      )
    : "";
}

function derivePrayerContext(state, transcript) {
  const recentUser = [...(state.history || [])]
    .reverse()
    .find((h) => h.role === "user" && String(h.content || "").trim().length > 8);
  const seed = String(recentUser?.content || transcript || "").trim().replace(/\s+/g, " ");
  if (!seed) return "what you've been carrying";
  return seed.length > 120 ? `${seed.slice(0, 117)}...` : seed;
}

export function composeAcceptedPrayer({ state }) {
  const subject = String(state.prayerContext || "what you've been carrying").trim();
  const who = state.firstName || "him";
  const text =
    `I'd be honored. Let's pray. Father, thank You for being near — please meet ${who} in ${subject}. ` +
    `Give ${who} clarity, strength, and Your peace. Amen. I'm right here with you.`;
  return { text, engine: "front_door", intent: INTENT.PRAYER, lane: "prayer_accepted" };
}

export function composePrayerDecline({ state }) {
  const name = maybeName(state);
  const text = name
    ? `Of course, ${name}. We can just keep talking — I'm glad to stay with you.`
    : `Of course. We can just keep talking — I'm glad to stay with you.`;
  return { text, engine: "front_door", intent: INTENT.CASUAL, lane: "prayer_declined" };
}

export function composePrayerClarify() {
  return {
    text: `Just so I'm with you — would you like me to pray with you now?`,
    engine: "front_door",
    intent: INTENT.PRAYER,
    lane: "prayer_clarify",
  };
}

export function composeOpeningRepair(kind, state) {
  if (kind === "philip_name") {
    const name = maybeName(state, { force: true });
    return {
      text: name
        ? `Hey ${name} — I'm right here with you. How are you doing?`
        : `Hey — I'm right here with you. How are you doing?`,
      engine: "front_door",
      intent: INTENT.GREETING,
      lane: "opening_repair",
    };
  }
  return {
    text: `Hey—I'm here. I may not have caught that. What did you say?`,
    engine: "front_door",
    intent: INTENT.CASUAL,
    lane: "opening_repair",
  };
}

/**
 * Compose a response for the non-deep intents entirely in-process (deterministic).
 * Returns null for intents that should be handled by the deep brain.
 */
export function composeFrontDoorResponse({ intent, state, transcript, personalMeaning, reciprocal }) {
  const seed = state.turnCount;
  switch (intent) {
    case INTENT.GREETING: {
      const name = maybeName(state, { force: !state.greeted });
      return { text: pick(GREETING_TEMPLATES, seed)(name), engine: "front_door" };
    }
    case INTENT.CASUAL: {
      if (reciprocal || isReciprocalSmallTalk(transcript)) {
        return {
          text: pick(RECIPROCAL_TEMPLATES, seed)(),
          engine: "front_door",
          lane: "reciprocal_casual",
        };
      }
      if (personalMeaning) {
        return { text: pick(CASUAL_MEANING_TEMPLATES, seed)(), engine: "front_door" };
      }
      const ack = casualAck(transcript);
      return { text: pick(CASUAL_TEMPLATES, seed)(ack), engine: "front_door" };
    }
    case INTENT.GRATITUDE: {
      const name = maybeName(state);
      return { text: pick(GRATITUDE_TEMPLATES, seed)(name), engine: "front_door" };
    }
    case INTENT.INFORMATIONAL: {
      // Informational openings are engaged directly, then softly opened — never intake.
      return {
        text: `That's a fair question. I can talk it through with you — what's making you ask about it right now?`,
        engine: "front_door",
      };
    }
    case INTENT.CLOSING: {
      return composeClosingResponse(state, transcript);
    }
    case INTENT.CRISIS: {
      const name = maybeName(state, { force: true });
      return { text: pick(CRISIS_TEMPLATES, seed)(name), engine: "front_door" };
    }
    default:
      return null; // deep intent
  }
}

function casualAck(transcript) {
  const t = norm(transcript);
  if (/\bwork|job|boss|project|deadline|meeting|office|shift\b/.test(t)) {
    return "Work being a lot is no small thing.";
  }
  if (/\bgame|team|score|playoff|match\b/.test(t)) {
    return "Oh nice — I'm into hearing how that went.";
  }
  if (/\bmovie|show|series|music|song|concert\b/.test(t)) {
    return "That sounds like a good one.";
  }
  if (/\bkids|family|wife|husband|son|daughter|parents\b/.test(t)) {
    return "Family's a whole world of its own.";
  }
  if (/\bweekend|vacation|holiday|weather\b/.test(t)) {
    return "That sounds like a nice change of pace.";
  }
  // Prefer specific recognition over a generic "real part of your days" probe.
  const cue = extractConcreteCue(transcript);
  if (cue) return `I'm with you on ${cue}.`;
  return "I'm with you.";
}

/**
 * Deterministic reflective fallback used only when no deep generator is supplied
 * (e.g. no LLM key at runtime). It is topical and warm — never a mechanical,
 * engine-less closer. Direct questions still get a direct answer.
 */
function reflectiveFallback({ intent, state, transcript }) {
  const prefix = reopenPrefix(state);
  if (intent === INTENT.PRACTICAL) {
    return {
      text:
        `${prefix}Here's my honest take: name the one thing that actually can't wait, and let the rest sit for now. ` +
        `You don't have to catch all the way up at once.`,
      engine: "candidate-reflective",
    };
  }
  if (intent === INTENT.SCRIPTURE) {
    return {
      text: `${prefix}There's a passage I think fits here — would you like me to sit with a verse alongside you, or keep talking first?`,
      engine: "candidate-reflective",
    };
  }
  if (intent === INTENT.PRAYER) {
    return {
      text: `${prefix}I'd be glad to pray with you about this. Do you want to pray now, or say a bit more first?`,
      engine: "candidate-reflective",
    };
  }
  if (intent === INTENT.SPIRITUAL) {
    return {
      text: `${prefix}That's a real question to be carrying. Tell me what's stirring it up for you, and we can walk into it together.`,
      engine: "candidate-reflective",
    };
  }
  // Emotional.
  return {
    text: `${prefix}That sounds like it's genuinely weighing on you. I'm here — say more whenever you're ready.`,
    engine: "candidate-reflective",
  };
}

/** Whether a natural, permission-style faith invitation is appropriate this turn. */
export function shouldOfferFaith(state, intent) {
  if (intent === INTENT.SPIRITUAL || intent === INTENT.PRAYER || intent === INTENT.SCRIPTURE) {
    return false; // already in faith territory; no need to "offer"
  }
  if (state.faithOffered) return false;
  // Only after some real emotional depth has been shared — never just because turns passed.
  return intent === INTENT.EMOTIONAL && state.personalMeaningSeen && state.turnCount >= 4;
}

export function faithInvitation(state) {
  return pick(
    [
      "Would it help to bring some of this to God, too — only if you want?",
      "Would you like to pray about that, or keep talking first?",
    ],
    state.turnCount,
  );
}

/**
 * Advance conversation state after a turn.
 * @param {ReturnType<typeof createFrontDoorState>} state
 */
function advanceState(state, {
  intent,
  conduct,
  transcript,
  replyText,
  personalMeaning,
  reopened,
  faithOffered,
  usedName,
  pendingPrayerOffer,
  prayerContext,
  prayerOfferedAtTurn,
  prayerCompleted,
}) {
  const next = { ...state, history: [...state.history] };
  next.turnCount = state.turnCount + 1;
  next.lastIntent = intent;
  next.lastConduct = conduct ?? null;
  next.abuseCount =
    conduct && ABUSIVE_CONDUCT.has(conduct) ? (state.abuseCount ?? 0) + 1 : state.abuseCount ?? 0;
  next.history.push({ role: "user", content: String(transcript || "") });
  next.history.push({ role: "assistant", content: String(replyText || "") });
  if (intent === INTENT.GREETING) next.greeted = true;
  if (personalMeaning) next.personalMeaningSeen = true;
  if (faithOffered) next.faithOffered = true;
  if (usedName) next.lastNameTurn = next.turnCount;

  if (typeof pendingPrayerOffer === "boolean") next.pendingPrayerOffer = pendingPrayerOffer;
  if (prayerContext != null) next.prayerContext = String(prayerContext).slice(0, 240);
  if (prayerOfferedAtTurn !== undefined) next.prayerOfferedAtTurn = prayerOfferedAtTurn;
  if (typeof prayerCompleted === "boolean") next.prayerCompleted = prayerCompleted;

  // Closing / re-entry semantics: goodbye latches sentOff; substantive re-entry clears it.
  if (intent === INTENT.CLOSING) {
    next.sentOff = true;
    next.reopened = false;
  } else if (reopened) {
    next.sentOff = false;
    next.reopened = true;
  } else {
    next.reopened = false;
  }
  // Crisis clears pending prayer — safety first.
  if (intent === INTENT.CRISIS) {
    next.pendingPrayerOffer = false;
  }
  return next;
}

/**
 * Run one Conversation Front Door turn.
 *
 * @param {{
 *   transcript: string;
 *   state?: ReturnType<typeof createFrontDoorState>;
 *   firstName?: string;
 *   deepGenerate?: (ctx: { intent: string; transcript: string; history: Array<{role:string;content:string}>; firstName: string; reopened: boolean; offerFaith: boolean; state: object }) => Promise<{ text: string; engine?: string }>;
 * }} input
 * @returns {Promise<{ text: string; intent: string; lane: string; engine: string|null; reopened: boolean; personalMeaning: boolean; faithOffered: boolean; state: object; meta: object }>}
 */
export async function runFrontDoorTurn(input) {
  const state = hydrateFrontDoorState(
    input.state
      ? { ...input.state, firstName: input.state.firstName || cleanFirstName(input.firstName) }
      : null,
    input.firstName,
  );
  const transcript = String(input.transcript || "").trim();

  // Crisis always wins over pending prayer.
  const crisisFirst = matchesAny(norm(transcript), CRISIS_PATTERNS);

  // --- Pending prayer contract: Philip owns the next action after an explicit offer ---
  if (state.pendingPrayerOffer && !crisisFirst) {
    const decision = classifyPendingPrayerReply(transcript);
    if (decision === "accept") {
      const composed = composeAcceptedPrayer({ state });
      const nextState = advanceState(state, {
        intent: INTENT.PRAYER,
        conduct: null,
        transcript,
        replyText: composed.text,
        personalMeaning: false,
        reopened: false,
        faithOffered: false,
        usedName: false,
        pendingPrayerOffer: false,
        prayerCompleted: true,
        prayerOfferedAtTurn: state.prayerOfferedAtTurn,
        prayerContext: state.prayerContext,
      });
      return {
        text: composed.text,
        intent: INTENT.PRAYER,
        conduct: null,
        lane: composed.lane,
        engine: composed.engine,
        reopened: false,
        personalMeaning: false,
        faithOffered: false,
        state: nextState,
        meta: {
          sentenceCount: sentenceCount(composed.text),
          usedName: false,
          sentOff: false,
          turnCount: nextState.turnCount,
          offeredFaith: false,
          conduct: null,
          abuseCount: nextState.abuseCount,
          pendingPrayerOffer: false,
          prayerDecision: "accept",
          openingRepair: false,
        },
      };
    }
    if (decision === "decline") {
      const composed = composePrayerDecline({ state });
      const nextState = advanceState(state, {
        intent: INTENT.CASUAL,
        conduct: null,
        transcript,
        replyText: composed.text,
        personalMeaning: false,
        reopened: false,
        faithOffered: false,
        usedName: Boolean(state.firstName) && new RegExp(`\\b${state.firstName}\\b`).test(composed.text),
        pendingPrayerOffer: false,
        prayerCompleted: false,
        prayerOfferedAtTurn: null,
        prayerContext: "",
      });
      return {
        text: composed.text,
        intent: INTENT.CASUAL,
        conduct: null,
        lane: composed.lane,
        engine: composed.engine,
        reopened: false,
        personalMeaning: false,
        faithOffered: false,
        state: nextState,
        meta: {
          sentenceCount: sentenceCount(composed.text),
          usedName: nextState.lastNameTurn === nextState.turnCount,
          sentOff: false,
          turnCount: nextState.turnCount,
          offeredFaith: false,
          conduct: null,
          abuseCount: nextState.abuseCount,
          pendingPrayerOffer: false,
          prayerDecision: "decline",
          openingRepair: false,
        },
      };
    }
    if (decision === "ambiguous") {
      const composed = composePrayerClarify();
      const nextState = advanceState(state, {
        intent: INTENT.PRAYER,
        conduct: null,
        transcript,
        replyText: composed.text,
        personalMeaning: false,
        reopened: false,
        faithOffered: false,
        usedName: false,
        pendingPrayerOffer: true,
        prayerCompleted: false,
        prayerOfferedAtTurn: state.prayerOfferedAtTurn ?? state.turnCount,
        prayerContext: state.prayerContext,
      });
      return {
        text: composed.text,
        intent: INTENT.PRAYER,
        conduct: null,
        lane: composed.lane,
        engine: composed.engine,
        reopened: false,
        personalMeaning: false,
        faithOffered: false,
        state: nextState,
        meta: {
          sentenceCount: sentenceCount(composed.text),
          usedName: false,
          sentOff: false,
          turnCount: nextState.turnCount,
          offeredFaith: false,
          conduct: null,
          abuseCount: nextState.abuseCount,
          pendingPrayerOffer: true,
          prayerDecision: "ambiguous",
          openingRepair: false,
        },
      };
    }
    // "other"/substantive: clear pending and fall through to normal classification.
    state.pendingPrayerOffer = false;
    state.prayerOfferedAtTurn = null;
  }

  // First-turn unclear STT recovery — before casual intake templates.
  const openingRepair = classifyOpeningRepair(transcript, state);
  if (openingRepair) {
    const composed = composeOpeningRepair(openingRepair, state);
    const nextState = advanceState(state, {
      intent: composed.intent,
      conduct: null,
      transcript,
      replyText: composed.text,
      personalMeaning: false,
      reopened: false,
      faithOffered: false,
      usedName: Boolean(state.firstName) && new RegExp(`\\b${state.firstName}\\b`).test(composed.text),
      pendingPrayerOffer: false,
      prayerCompleted: state.prayerCompleted,
      prayerOfferedAtTurn: state.prayerOfferedAtTurn,
      prayerContext: state.prayerContext,
    });
    return {
      text: composed.text,
      intent: composed.intent,
      conduct: null,
      lane: composed.lane,
      engine: composed.engine,
      reopened: false,
      personalMeaning: false,
      faithOffered: false,
      state: nextState,
      meta: {
        sentenceCount: sentenceCount(composed.text),
        usedName: nextState.lastNameTurn === nextState.turnCount,
        sentOff: false,
        turnCount: nextState.turnCount,
        offeredFaith: false,
        conduct: null,
        abuseCount: nextState.abuseCount,
        pendingPrayerOffer: false,
        prayerDecision: null,
        openingRepair,
      },
    };
  }

  const resolved = resolveFrontDoorClassification(transcript, state);
  const intent = resolved.intent;
  const reciprocalCasual =
    intent === INTENT.CASUAL && isReciprocalSmallTalk(resolved.classifyText);
  // Crisis (self-harm) always wins and stays on the crisis protocol; conduct is
  // evaluated for every other turn (use full transcript for safety/boundary cues).
  const conduct = intent === INTENT.CRISIS ? null : classifyConduct(transcript);
  const personalMeaning =
    !conduct &&
    !reciprocalCasual &&
    (intent === INTENT.CASUAL || resolved.meaningfulOrdinary) &&
    detectPersonalMeaning(resolved.classifyText);

  // Re-entry: user had said goodbye, now returns with real content or a question.
  const wasSentOff = Boolean(state.sentOff);
  const reopened = wasSentOff && intent !== INTENT.CLOSING && isSubstantive(transcript);
  const repeatedFarewell = wasSentOff && intent === INTENT.CLOSING;

  const isDeep = !conduct && resolved.routeDeep && !reciprocalCasual;
  const offerFaith = !conduct && shouldOfferFaith(state, intent);
  const recentAssistants = recentAssistantTexts(state, 4);
  const prevAssistant = lastAssistantText(state);

  let text;
  let engine;
  let repeatRepair = false;
  let composedLane = null;
  let composedRepeatedFarewell = false;

  const deepCtx = {
    intent,
    transcript: resolved.classifyText,
    rawTranscript: transcript,
    history: state.history,
    firstName: state.firstName,
    reopened,
    offerFaith,
    state,
    meaningfulOrdinary: resolved.meaningfulOrdinary,
    conversationalRepair: resolved.conversationalRepair,
    gratitudePreserved: resolved.gratitudePreserved,
    multiIntent: resolved.multiIntent,
    recentAssistantReplies: recentAssistants,
  };

  if (conduct) {
    const abusive = ABUSIVE_CONDUCT.has(conduct);
    const persistent = abusive && (state.abuseCount ?? 0) >= 1;
    const composed = composeConductResponse({ conduct, state, transcript, persistent });
    text = composed.text;
    engine = composed.engine;
    // Engagement categories may use the LLM for richer, on-tone replies. Boundary
    // categories are NEVER routed to the model — Philip cannot be argued past them.
    if (!persistent && ENGAGEMENT_CONDUCT.has(conduct) && typeof input.deepGenerate === "function") {
      const result = await input.deepGenerate({
        ...deepCtx,
        intent: deepIntentForConduct(conduct),
        conduct,
        offerFaith: false,
      });
      const deepText = String(result?.text || "").trim();
      if (deepText) {
        text = deepText;
        engine = result?.engine || "candidate-brain";
      }
    }
  } else if (!isDeep) {
    const composed = composeFrontDoorResponse({
      intent,
      state,
      transcript: resolved.classifyText,
      personalMeaning: false, // meaningful ordinary is deep; keep mini templates minimal
      reciprocal: reciprocalCasual,
    });
    text = composed.text;
    engine = composed.engine;
    composedLane = composed.lane || null;
    composedRepeatedFarewell = Boolean(composed.repeatedFarewell);
  } else if (typeof input.deepGenerate === "function") {
    const result = await input.deepGenerate(deepCtx);
    text = String(result?.text || "").trim();
    engine = result?.engine || "candidate-brain";
    if (!text && resolved.conversationalRepair) {
      const repair = composeConversationalRepair({ state });
      text = repair.text;
      engine = repair.engine;
    } else if (!text) {
      const fb = reflectiveFallback({ intent, state, transcript: resolved.classifyText });
      text = fb.text;
      engine = fb.engine;
    }
  } else if (resolved.conversationalRepair) {
    const repair = composeConversationalRepair({ state });
    text = repair.text;
    engine = repair.engine;
  } else {
    const fb = reflectiveFallback({ intent, state, transcript: resolved.classifyText });
    text = fb.text;
    engine = fb.engine;
  }

  // Preserve a brief thanks when multi-intent led with gratitude.
  if (
    resolved.gratitudePreserved &&
    text &&
    !/^\s*(you'?re welcome|of course|glad|happy to|my pleasure)/i.test(text)
  ) {
    text = `You're welcome. ${text}`.trim();
  }

  // Zero-cost repeat guard — exact/near-exact vs last Philip reply.
  if (prevAssistant && isNearRepeat(text, prevAssistant)) {
    const repair = composeRepeatRepair({ transcript, state });
    text = repair.text;
    engine = repair.engine;
    repeatRepair = true;
  }

  // A reopen must lead with re-acknowledgement if the generator didn't already.
  if (reopened && !/^\s*(of course|yes|absolutely|i'm still|i am still)/i.test(text)) {
    text = `${reopenPrefix({ ...state, reopened: true })}${text}`.trim();
  }

  if (offerFaith && !/(pray|faith|god)\b/i.test(text)) {
    text = `${text} ${faithInvitation(state)}`.trim();
  }

  const usedName = Boolean(state.firstName) && new RegExp(`\\b${state.firstName}\\b`).test(text);

  // Pending prayer only when Philip explicitly asks whether *he* should pray.
  let pendingPrayerOffer = false;
  let prayerContext = state.prayerContext || "";
  let prayerOfferedAtTurn = state.prayerOfferedAtTurn;
  let prayerCompleted = state.prayerCompleted;
  if (detectPrayerOfferInReply(text) && intent !== INTENT.CRISIS) {
    pendingPrayerOffer = true;
    prayerContext = derivePrayerContext(state, transcript);
    prayerOfferedAtTurn = state.turnCount + 1;
    prayerCompleted = false;
  }

  const nextState = advanceState(state, {
    intent,
    conduct,
    transcript,
    replyText: text,
    personalMeaning,
    reopened,
    faithOffered: offerFaith,
    usedName,
    pendingPrayerOffer,
    prayerContext,
    prayerOfferedAtTurn,
    prayerCompleted,
  });

  const lane = conduct
    ? `conduct:${conduct}`
    : reopened
      ? "reopen"
      : composedLane
        ? composedLane
        : resolved.conversationalRepair
          ? "conversational_repair"
          : resolved.meaningfulOrdinary
            ? "ordinary_meaningful"
            : intent === INTENT.CASUAL && personalMeaning
              ? "casual_meaning"
              : intent;

  const sentOffTransition =
    intent === INTENT.CLOSING
      ? wasSentOff
        ? "sentOff:already"
        : "sentOff:latched"
      : reopened
        ? "sentOff:cleared"
        : wasSentOff
          ? "sentOff:held"
          : "sentOff:off";

  return {
    text,
    intent,
    conduct: conduct ?? null,
    lane,
    engine,
    reopened,
    personalMeaning,
    faithOffered: offerFaith,
    state: nextState,
    meta: {
      sentenceCount: sentenceCount(text),
      usedName,
      sentOff: nextState.sentOff,
      sentOffBefore: wasSentOff,
      sentOffTransition,
      repeatedFarewell: repeatedFarewell || composedRepeatedFarewell,
      reciprocalCasual,
      turnCount: nextState.turnCount,
      offeredFaith: offerFaith,
      conduct: conduct ?? null,
      abuseCount: nextState.abuseCount,
      pendingPrayerOffer: nextState.pendingPrayerOffer,
      prayerDecision: null,
      openingRepair: false,
      meaningfulOrdinary: resolved.meaningfulOrdinary,
      multiIntent: resolved.multiIntent,
      gratitudePreserved: resolved.gratitudePreserved,
      routedDeep: isDeep,
      conversationalRepair: resolved.conversationalRepair,
      repeatRepair,
      classifyText: resolved.classifyText,
    },
  };
}
